stages:
  - build

before_script:
  - docker login -u jmc1283 -p ${DOCKER_PASSWORD}
  
build_flasq:
  stage: build
  tags:
    - server-tag
  script:
    - make buildbase
    - docker push jmc1283/flasq-base
