version: '3'

services:
  flasq:
    build: .
    expose:
      - "5000"
    ports:
      - "443:5000"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/route/to/data:/home/flasq/${SITENAME}/web/data"
