version: '2'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"
      - "traefik.backend=traefik"
      # - "traefik.port=8080"
      # - "traefik.frontend.auth.basic.users={user:hash}"
      # - "traefik.frontend.rule=Host:traefik.{domain}"
    networks:
      - traefik-proxy

  
  flasq:
    build: .
    restart: always
    expose:
      - "80"
    volumes:
      - "./.data:/flasq/.data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flasq"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:"
    environment:
      - "PORT=80"
      - "WORKERS=4"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
