version: '3'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.port=8080"
      - "traefik.enabled=true"
      - "traefik.backend=traefik"
      # - "traefik.frontend.auth.basic.users={user:hash}"
      # - "traefik.frontend.rule=Host:traefik.{domain}"
    networks:
      - traefik-proxy

  
  flasq:
    build: .
    restart: always
    expose:
      - "80"
    volumes:
      - "./web/.data:/flasq/web/.data"
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=traefik"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:{domain}"
    environment:
      - "PORT=80"
      - "WORKERS=4"
      - "SITENAME={websitename}"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
